version: "3.8"
services:
  database:
    restart: always
    build:
      context: .
      dockerfile: database.Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mande
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./packages/database/data:/var/lib/postgresql/data/

  server:
    restart: always
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - ./packages/server/uploads:/server/uploads

  frontend:
    build:
      context: .
      dockerfile: client.Dockerfile
    restart: always
    depends_on:
      - server
    ports:
      - 3000:3000
